/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.springframework.samples.petclinic.rest.api

import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import jakarta.validation.Valid
import jakarta.validation.constraints.Min
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.samples.petclinic.rest.dto.PetDto
import org.springframework.samples.petclinic.rest.dto.PetFieldsDto
import org.springframework.samples.petclinic.rest.dto.RestErrorDto
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@Validated
@RequestMapping("\${api.base-path:/petclinic/api}")
interface PetsApi {

    @Operation(
        summary = "Create a pet",
        operationId = "addPet",
        description = """Creates a pet .""",
        responses = [
            ApiResponse(
                responseCode = "200",
                description = "Pet type created successfully.",
                content = [Content(schema = Schema(implementation = PetDto::class))]
            ),
            ApiResponse(responseCode = "304", description = "Not modified."),
            ApiResponse(
                responseCode = "400",
                description = "Bad request.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            ),
            ApiResponse(
                responseCode = "404",
                description = "Pet not found.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            ),
            ApiResponse(
                responseCode = "500",
                description = "Server error.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            )
        ]
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/pets"],
        produces = ["application/json"],
        consumes = ["application/json"]
    )
    fun addPet(
        @Parameter(
            description = "The pet",
            required = true
        ) @Valid @RequestBody petDto: PetDto
    ): ResponseEntity<PetDto> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        summary = "Delete a pet by ID",
        operationId = "deletePet",
        description = """Returns the pet or a 404 error.""",
        responses = [
            ApiResponse(
                responseCode = "200",
                description = "Pet details found and returned.",
                content = [Content(schema = Schema(implementation = PetDto::class))]
            ),
            ApiResponse(responseCode = "304", description = "Not modified."),
            ApiResponse(
                responseCode = "400",
                description = "Bad request.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            ),
            ApiResponse(
                responseCode = "404",
                description = "Pet not found.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            ),
            ApiResponse(
                responseCode = "500",
                description = "Server error.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            )
        ]
    )
    @RequestMapping(
        method = [RequestMethod.DELETE],
        value = ["/pets/{petId}"],
        produces = ["application/json"]
    )
    fun deletePet(
        @Min(0) @Parameter(
            description = "The ID of the pet.",
            required = true
        ) @PathVariable("petId") petId: Int
    ): ResponseEntity<PetDto> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        summary = "Get a pet by ID",
        operationId = "getPet",
        description = """Returns the pet  or a 404 error.""",
        responses = [
            ApiResponse(
                responseCode = "200",
                description = "Pet details found and returned.",
                content = [Content(schema = Schema(implementation = PetDto::class))]
            ),
            ApiResponse(responseCode = "304", description = "Not modified."),
            ApiResponse(
                responseCode = "400",
                description = "Bad request.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            ),
            ApiResponse(
                responseCode = "404",
                description = "Pet not found.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            ),
            ApiResponse(
                responseCode = "500",
                description = "Server error.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            )
        ]
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/pets/{petId}"],
        produces = ["application/json"]
    )
    fun getPet(
        @Min(0) @Parameter(
            description = "The ID of the pet.",
            required = true
        ) @PathVariable("petId") petId: Int
    ): ResponseEntity<PetDto> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        summary = "Lists pet",
        operationId = "listPets",
        description = """Returns an array of pet .""",
        responses = [
            ApiResponse(
                responseCode = "200",
                description = "Pet types found and returned.",
                content = [Content(schema = Schema(implementation = PetDto::class))]
            ),
            ApiResponse(responseCode = "304", description = "Not modified."),
            ApiResponse(
                responseCode = "500",
                description = "Server error.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            )
        ]
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/pets"],
        produces = ["application/json"]
    )
    fun listPets(): ResponseEntity<List<PetDto>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        summary = "Update a pet by ID",
        operationId = "updatePet",
        description = """Returns the pet or a 404 error.""",
        responses = [
            ApiResponse(
                responseCode = "200",
                description = "Pet details found and returned.",
                content = [Content(schema = Schema(implementation = PetDto::class))]
            ),
            ApiResponse(responseCode = "304", description = "Not modified."),
            ApiResponse(
                responseCode = "400",
                description = "Bad request.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            ),
            ApiResponse(
                responseCode = "404",
                description = "Pet not found.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            ),
            ApiResponse(
                responseCode = "500",
                description = "Server error.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            )
        ]
    )
    @RequestMapping(
        method = [RequestMethod.PUT],
        value = ["/pets/{petId}"],
        produces = ["application/json"],
        consumes = ["application/json"]
    )
    fun updatePet(
        @Min(0) @Parameter(
            description = "The ID of the pet.",
            required = true
        ) @PathVariable("petId") petId: Int,
        @Parameter(description = "The pet", required = true) @Valid @RequestBody petFieldsDto: PetFieldsDto
    ): ResponseEntity<PetDto> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
