/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.springframework.samples.petclinic.rest.api

import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import jakarta.validation.Valid
import jakarta.validation.constraints.Min
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.samples.petclinic.rest.dto.RestErrorDto
import org.springframework.samples.petclinic.rest.dto.VisitDto
import org.springframework.samples.petclinic.rest.dto.VisitFieldsDto
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@Validated
@RequestMapping("\${api.base-path:/petclinic/api}")
interface VisitsApi {

    @Operation(
        summary = "Create a visit",
        operationId = "addVisit",
        description = """Creates a visit.""",
        responses = [
            ApiResponse(
                responseCode = "200",
                description = "visit created successfully.",
                content = [Content(schema = Schema(implementation = VisitDto::class))]
            ),
            ApiResponse(responseCode = "304", description = "Not modified."),
            ApiResponse(
                responseCode = "400",
                description = "Bad request.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            ),
            ApiResponse(
                responseCode = "404",
                description = "Visit not found.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            ),
            ApiResponse(
                responseCode = "500",
                description = "Server error.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            )
        ]
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/visits"],
        produces = ["application/json"],
        consumes = ["application/json"]
    )
    fun addVisit(
        @Parameter(
            description = "The visit",
            required = true
        ) @Valid @RequestBody visitDto: VisitDto
    ): ResponseEntity<VisitDto> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        summary = "Delete a visit by ID",
        operationId = "deleteVisit",
        description = """Returns the visit or a 404 error.""",
        responses = [
            ApiResponse(
                responseCode = "200",
                description = "Visit details found and returned.",
                content = [Content(schema = Schema(implementation = VisitDto::class))]
            ),
            ApiResponse(responseCode = "304", description = "Not modified."),
            ApiResponse(
                responseCode = "400",
                description = "Bad request.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            ),
            ApiResponse(
                responseCode = "404",
                description = "Visit not found.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            ),
            ApiResponse(
                responseCode = "500",
                description = "Server error.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            )
        ]
    )
    @RequestMapping(
        method = [RequestMethod.DELETE],
        value = ["/visits/{visitId}"],
        produces = ["application/json"]
    )
    fun deleteVisit(
        @Min(0) @Parameter(
            description = "The ID of the visit.",
            required = true
        ) @PathVariable("visitId") visitId: Int
    ): ResponseEntity<VisitDto> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        summary = "Get a visit by ID",
        operationId = "getVisit",
        description = """Returns the visit or a 404 error.""",
        responses = [
            ApiResponse(
                responseCode = "200",
                description = "Visit details found and returned.",
                content = [Content(schema = Schema(implementation = VisitDto::class))]
            ),
            ApiResponse(responseCode = "304", description = "Not modified."),
            ApiResponse(
                responseCode = "400",
                description = "Bad request.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            ),
            ApiResponse(
                responseCode = "404",
                description = "Visit not found.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            ),
            ApiResponse(
                responseCode = "500",
                description = "Server error.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            )
        ]
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/visits/{visitId}"],
        produces = ["application/json"]
    )
    fun getVisit(
        @Min(0) @Parameter(
            description = "The ID of the visit.",
            required = true
        ) @PathVariable("visitId") visitId: Int
    ): ResponseEntity<VisitDto> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        summary = "Lists visits",
        operationId = "listVisits",
        description = """Returns an array of visit .""",
        responses = [
            ApiResponse(
                responseCode = "200",
                description = "visits found and returned.",
                content = [Content(schema = Schema(implementation = VisitDto::class))]
            ),
            ApiResponse(responseCode = "304", description = "Not modified."),
            ApiResponse(
                responseCode = "500",
                description = "Server error.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            )
        ]
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/visits"],
        produces = ["application/json"]
    )
    fun listVisits(): ResponseEntity<List<VisitDto>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        summary = "Update a visit by ID",
        operationId = "updateVisit",
        description = """Returns the visit or a 404 error.""",
        responses = [
            ApiResponse(
                responseCode = "200",
                description = "Visit details found and returned.",
                content = [Content(schema = Schema(implementation = VisitDto::class))]
            ),
            ApiResponse(responseCode = "304", description = "Not modified."),
            ApiResponse(
                responseCode = "400",
                description = "Bad request.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            ),
            ApiResponse(
                responseCode = "404",
                description = "Visit not found.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            ),
            ApiResponse(
                responseCode = "500",
                description = "Server error.",
                content = [Content(schema = Schema(implementation = RestErrorDto::class))]
            )
        ]
    )
    @RequestMapping(
        method = [RequestMethod.PUT],
        value = ["/visits/{visitId}"],
        produces = ["application/json"],
        consumes = ["application/json"]
    )
    fun updateVisit(
        @Min(0) @Parameter(
            description = "The ID of the visit.",
            required = true
        ) @PathVariable("visitId") visitId: Int,
        @Parameter(description = "The visit", required = true) @Valid @RequestBody visitFieldsDto: VisitFieldsDto
    ): ResponseEntity<VisitDto> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
