# HSQLDB config start
#----------------------------------------------------------------

spring:
  sql:
    init:
      schema-locations: classpath*:db/hsqldb/initDB.sql
      data-locations: classpath*:db/hsqldb/populateDB.sql
  datasource:
    username: sa
    url: jdbc:hsqldb:mem:petclinic
    password: ''
  jpa:
    database: HSQL
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: none

#----------------------------------------------------------------
# HSQLDB config end
